name: Re-run PR workflows
description: Re-run GitHub workflows for incoming pull requests
inputs:
  github-token:
    description: The GitHub token used to authenticate against the GitHub APIs
    default: ${{ github.token }}
    required: false
  workflow:
    required: true
    description: The name of the workflow that should be re-run
runs:
  using: node20
  main: dist/index.js
