name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run all

    - name: Compare the expected and actual dist/ directories
      id: diff
      run: git diff --exit-code -- dist/

    # If dist/ was different than expected, upload the expected version as an artifact
    - name: Capture dist/ diff
      uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      with:
        name: dist
        path: dist/

    - name: Update rolling release tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git push origin HEAD:refs/tags/v0.2 --force
